### ISSUE TITLE
Vertical stacking issue

### ISSUE THREAD

**Issue by mgiako** [marcokreeft87/formulaone-card#134]
**Describe the bug**

First of all, beautiful card!
I have a problem with vertical stacking cards side by side.
I would like to use two or three columns to take advantage of all the space. But the result is different every time I refresh the page.
The problem occurs both with the GUI and in yaml mode
Has anyone else had this problem?

**To Reproduce**
I have a more complex config, but to reproduce the problem this is enough:
```
    title: F1
    path: f1
    cards:
      - type: vertical-stack
        cards:
          - type: custom:formulaone-card
            card_type: countdown
            show_raceinfo: true
      - type: vertical-stack
        cards:
          - type: custom:formulaone-card
            card_type: constructor_standings

```

**Screenshots**
First refresh:
![image](https://user-images.githubusercontent.com/44270368/216812643-cd41315e-2223-4795-a35e-cfddf4dec0ae.png)

Same config second refresh:
![image](https://user-images.githubusercontent.com/44270368/216812693-ddec44b6-932d-4ea7-9652-5f4b555cc1af.png)

**Additional context**
I'm on
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest 

OS: Windows10
Browser: Chrome
Version: 109.0.5414.120

**Comment by mgiako** [comment]
Tha layout changes even clicking on the icon to view/hide the side bar
![image](https://user-images.githubusercontent.com/44270368/216814841-1fbff752-a515-4e19-a496-55555e2855cc.png)

**Comment by marcokreeft87** [comment]
Try not using 1 vertical stack card and inside this card the formulaone-cards.

**Comment by marcokreeft87** [comment]
And thank you for the compliment!

**Comment by mgiako** [comment]
Thanks for the answer, but:
as I said my actual configuration is more complex:
```
  - title: F1
    path: f1

    cards:
      - type: vertical-stack
        cards:

          - type: custom:formulaone-card
            card_type: countdown        
            show_raceinfo: true     
            
          - type: custom:formulaone-card
            card_type: results

      - type: vertical-stack
        cards:
          - type: custom:formulaone-card
            card_type: driver_standings
            standings:
              show_flag: true
              show_team: true
              
          - type: custom:formulaone-card
            card_type: constructor_standings
            standings:
              show_teamlogo: true            

      - type: vertical-stack
        cards:
            
          - type: custom:formulaone-card
            card_type: schedule
            previous_race: italic
            date_locale: it
    
          - type: custom:formulaone-card
            card_type: qualifying_results
            standings:
```
If I don't use vertical stack, the single cards were disposed quite random by homeassistant.
I have other cards in other views where I use vertical stack to dispose the cards.
In those cases the visual layout of the cards is rock solid. And stable.

The problem only appears with F1 cards.
Not a big deal, I was just wondering if it only happens to me or others as well
