### ISSUE TITLE
Show Race Track Map enlarged

### ISSUE THREAD

**Issue by superpower10** [marcokreeft87/formulaone-card#179]
It would be nice if clicking/touching the map of the Race Track would enlarge it. 

That way it would be easier to details like speed traps, etc.

**Comment by marcokreeft87** [comment]
That's something you can do yourself with the actions :)

**Comment by Ndrinta** [comment]
I was thinking the same thing.
I'd like to add a tap_action to see the enlarged picture of the circuit, easy to say but it seems like you are using the png picture of the circuit straight from the formula1 website so it's not stored locally and I can't simply call it (and always find it with the same path/name).
Can you help us with this? How'd you do this?
Thanks

**Comment by marcokreeft87** [comment]
```
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.popup
    data:
      title: Mancave
      content:
        type: vertical-stack
        cards:
          - type: custom:formulaone-card
            card_type: next_race
            date_locale: nl
            show_raceinfo: true
            hide_racedatetimes: true
            f1_font: true
            show_weather: true


```

Maybe add something like that. Didnt test it, but it will point you in the right direction at least
