### ISSUE TITLE
`Next race` card only show track suddenly?

### ISSUE THREAD

**Issue by hmmbob** [marcokreeft87/formulaone-card#282]
**Describe the bug**
Maybe I missed a change, but looking back to the changelogs did not seem so. Since a few weeks (maybe?) I no longer see all the race info in the `next race` card, 

Live screenshot:

![image](https://github.com/marcokreeft87/formulaone-card/assets/33529490/0c698810-b8f7-4d7e-bb3d-f2615ca362cd)

**Expected behavior**
I was expecting the example layout: https://github.com/marcokreeft87/formulaone-card#next-race
![image](https://github.com/marcokreeft87/formulaone-card/assets/33529490/efd1277d-41b4-4c14-ae3e-aad9d7855aa9)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
All

**Additional context**
It did work before. Code is in line with the example code:

```yaml
          - card:
              type: custom:formulaone-card
              card_type: next_race
              title: Komende race
              date_locale: nl
              image_clickable: true
              f1_font: true
            attributes:
              icon: mdi:calendar-clock
``` 

(my full F1 view is here: https://github.com/hmmbob/HomeAssistantConfig/blob/master/dashboards/9-f1.yaml)
