### ISSUE TITLE
Error: Please pass the correct sensor (races)

### ISSUE THREAD

**Issue by Santanachia** [marcokreeft87/formulaone-card#33]
**Describe the bug**
after adding the card, an error appears

**Expected behavior**
if `state_attr('sensor.formula_one_sensor_races', 'next_race') == None` show information that there is no information, not an error that there is no sensor

**Screenshots**
![image](https://user-images.githubusercontent.com/4628507/208614495-fb3b075c-f8ec-47df-9d43-3b0f2cd45c01.png)

**Additional context**
```yaml
type: custom:formulaone-card
card_type: next_race
sensor: sensor.formula_one_sensor_races
title: Next Race
date_locale: pl
image_clickable: false
```
