### ISSUE TITLE
'Race' is not translated

### ISSUE THREAD

**Issue by hrw** [marcokreeft87/formulaone-card#343]
**Describe the bug**
There is a way to translate words in card described in README. I use it but 'Race' is not translated:

Code:
```yaml
type: custom:formulaone-card
card_type: next_race
title: Następny wyścig
f1_font: false
image_clickable: false
show_carnumber: false
show_raceinfo: true
hide_racedatetimes: false
only_show_date: false
hide_tracklayout: false
show_lastyears_result: true
show_weather: false
weather_options:
  show_icon: false
location_clickable: false
translations:
  date: Data
  city: Miasto
  practice1: Trening 1
  practice2: Trening 2
  practice3: Trening 3
  race: Runda
  racename: Wyścig
  circuitname: Tor
  location: Miejsce
  racet: Wyścig
  sprint: Sprint
  qualifying: Kwalifikacje
  endofseason: Season is over. See you next year!!

```

**Expected behavior**
'Miasto Melbourne Wyścig Sun 05:00' in last line.

**Screenshots**
![obraz](https://github.com/marcokreeft87/formulaone-card/assets/185508/3bfb6406-0e76-42a0-9bb6-3f9efa7918a1)

**Desktop:**
 - OS:     Fedora Linux 40
 - Browser Firefox
 - Version 123.0.1
