### ISSUE TITLE
Weather forecast doesn't work

### ISSUE THREAD

**Issue by Sarnog** [marcokreeft87/formulaone-card#347]
When i try to add the 'next race' card, i tried to add the forecast. When i try to input the api key and the unit via the gui, it doesn't get saved for some reason, so i tried to add it via the yaml edit:

```
type: custom:formulaone-card
card_type: next_race
title: Volgende Race
date_locale: nl
image_clickable: true
f1_font: true
show_weather: true
weather_options:
  unit: metric
  api_key: my-api-key
  show_cloud_cover: true
  show_wind: true
  show_icon: true
  show_precipitation: true
  show_temperature: true
  show_visibility: true
```

As soon as i saved it and review the yaml code, the 'unit: meteric' part, magicly disappeard from the code. Also there's no forecast info visable. At the place behind 'api_key: ' i enter ofcourse the api key that was send to me from the service, explained in the instruction documentation.

I use the latest version of home assistant os (OS, superviser and core all to the latest version) and the latest version of the integration.
