### ISSUE TITLE
Card won't load on Chrome or Edge (Windows)

### ISSUE THREAD

**Issue by pmharris77** [marcokreeft87/formulaone-card#349]
**Describe the bug**
I cannot get the card loading F1 data without error on Chrome or Edge on Windows.  Works fine on HA Android app.

See screenshot below.

**To Reproduce**

Add following card config to a dashboard:

```
type: custom:formulaone-card
card_type: next_race
f1_font: true
show_lastyears_result: false
show_raceinfo: true
show_weather: false
weather_options:
  show_cloud_cover: true
  show_wind: true
  show_visibility: false
  show_temperature: true
  show_precipitation: true
hide_racedatetimes: false
title: Next F1 Race

type: custom:formulaone-card
card_type: constructor_standings
standings:
  show_flag: true
  show_team: true
  show_teamlogo: true
f1_font: true
title: F1 Constructors Standings
```

**Expected behavior**
Card should load with correct data

**Screenshots**

![image](https://github.com/marcokreeft87/formulaone-card/assets/128244829/2c30da64-1771-4dd1-92aa-1b56f3649230)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro Build 22631
 - Browser : Chrome Version 123.0.6312.58 (Official Build) (64-bit) , Edge Version 122.0.2365.92 (Official build) (64-bit)
