### ISSUE TITLE
Country Flags not loading

### ISSUE THREAD

**Issue by n00bcodr** [marcokreeft87/formulaone-card#41]
**Describe the bug**
Country flags in drivers' standings not loading.

**To Reproduce**
Add a card with the below config

```
type: custom:formulaone-card
card_type: driver_standings
sensor: sensor.formula_one_sensor_drivers
title: Driver Standings
standings:
  show_flag: true
  show_team: true
```

**Expected behavior**
Country Flags should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/49611451/209787263-61dcefc9-67d0-4c6e-afbd-9e3132f2113f.png)

**Desktop (please complete the following information):**
- not browser specific. 

**Smartphone (please complete the following information):**
- not browser specific. 

**Additional context**
Looks like the site https://www.countries-ofthe-world.com/ is down.
May be a better way is to have the images locally, for quick loading?
